repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      name: trimming whitespaces
- repo: https://github.com/bwbaugh/haskell-pre-commit-hooks.git
  rev: v0.2.1
  hooks:
    - id: stylish-haskell
    - id: hlint
