repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      name: trimming whitespaces
- repo: https://github.com/bwbaugh/haskell-pre-commit-hooks.git
  rev: v0.2.1
  hooks:
    - id: stylish-haskell
    - id: hlint
- repo: https://github.com/algoritmist/haskell-golden-tests-pre-commit-hook.git
  rev: 125db9c8ad8d84040c2bf643b1894f91de5c2fb1
  hooks:
    - id: golden-test
      name: Run golden tests
      description: This hook runs golden tests before commit
      language: system
      pass_filenames: false
      entry: cabal run Golden-tests
    - id: golden-test
      name: Run unit tests
      description: This hook runs golden tests before commit
      language: system
      pass_filenames: false
      entry: cabal run Unit-tests

